name: intake-demo
channels:
  - conda-forge
  - informaticslab
dependencies:
  - python=3
  - geopandas>=0.5
  - intake>=0.5.0
  - intake_geopandas>=0.2.2
  - gdal>=2.4
  - dask>=1.2.0
  - postgis
  - pip:
    - jupyterlab==1.0.0a3
    - intake-dcat==0.2.0
